version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  fedora:
    image: osul/fcrepo:4.6.0
  solr:
    build:
      context: .
      dockerfile: ./lib/support/docker/Dockerfile-solr
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/hydra-docker-demo
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - fedora
      - solr
