development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fedora:8080/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fedora:8080/fcrepo/rest
  base_path: /test
